POST http://localhost:3001/api/blogs 
content-type: application/json

{
    "title": "Testing",
    "author": "Edward",
    "url": "http://localhost:3001/api/",
    "likes": "50"
}
###
GET http://localhost:3001/api/blogs 
###
DELETE http://localhost:3001/api/blogs/62a20c68410d9bb06d09cd16